USE [master]
GO
/****** Object:  Database [LibMSDb]    Script Date: 9/14/2020 1:41:42 PM ******/
CREATE DATABASE [LibMSDb]
GO
ALTER DATABASE [LibMSDb] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LibMSDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LibMSDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LibMSDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LibMSDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LibMSDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LibMSDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [LibMSDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LibMSDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LibMSDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LibMSDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LibMSDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LibMSDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LibMSDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LibMSDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LibMSDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LibMSDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LibMSDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LibMSDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LibMSDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LibMSDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LibMSDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LibMSDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LibMSDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LibMSDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [LibMSDb] SET  MULTI_USER 
GO
ALTER DATABASE [LibMSDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LibMSDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LibMSDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LibMSDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [LibMSDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [LibMSDb] SET QUERY_STORE = OFF
GO
USE [LibMSDb]
GO
/****** Object:  Table [dbo].[AssignBookInfo]    Script Date: 9/14/2020 1:41:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AssignBookInfo](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[BookId] [int] NOT NULL,
	[IsReturned] [bit] NOT NULL,
 CONSTRAINT [PK_AssignBookInfo] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BookCountInfo]    Script Date: 9/14/2020 1:41:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BookCountInfo](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BookID] [int] NULL,
	[BookCount] [int] NULL,
 CONSTRAINT [PK_BookCountInfo] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BookInfo]    Script Date: 9/14/2020 1:41:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BookInfo](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](500) NULL,
	[Details] [nvarchar](500) NULL,
 CONSTRAINT [PK_BookInfo] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 9/14/2020 1:41:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](500) NULL,
	[LastName] [nvarchar](500) NULL,
	[UserName] [nvarchar](500) NULL,
	[Password] [nvarchar](500) NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AssignBookInfo]  WITH CHECK ADD  CONSTRAINT [FK_AssignBookInfo_BookInfo] FOREIGN KEY([BookId])
REFERENCES [dbo].[BookInfo] ([ID])
GO
ALTER TABLE [dbo].[AssignBookInfo] CHECK CONSTRAINT [FK_AssignBookInfo_BookInfo]
GO
ALTER TABLE [dbo].[AssignBookInfo]  WITH CHECK ADD  CONSTRAINT [FK_AssignBookInfo_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([ID])
GO
ALTER TABLE [dbo].[AssignBookInfo] CHECK CONSTRAINT [FK_AssignBookInfo_User]
GO
ALTER TABLE [dbo].[BookCountInfo]  WITH CHECK ADD  CONSTRAINT [FK_BookCountInfo_BookInfo] FOREIGN KEY([BookID])
REFERENCES [dbo].[BookInfo] ([ID])
GO
ALTER TABLE [dbo].[BookCountInfo] CHECK CONSTRAINT [FK_BookCountInfo_BookInfo]
GO
USE [master]
GO
ALTER DATABASE [LibMSDb] SET  READ_WRITE 
GO
